[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
abstract_mainnet = "${ABSTRACT_MAINNET_RPC_URL}"
abstract_testnet = "${ABSTRACT_TESTNET_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"
base_testnet = "${BASE_TESTNET_RPC_URL}"
merlin_mainnet = "${MERLIN_MAINNET_RPC_URL}"
merlin_testnet = "${MERLIN_TESTNET_RPC_URL}"
arbitrum_one = "${ARBITRUM_ONE_RPC_URL}"
arbitrum_testnet = "${ARBITRUM_TESTNET_RPC_URL}"
apechain_mainnet = "${APECHAIN_MAINNET_RPC_URL}"
apechain_testnet = "${APECHAIN_TESTNET_RPC_URL}"

[profile.etherscan_endpoints]
etherscan = "${ETHERSCAN_API_KEY}"
abstractscan_mainnet = "${ABSTRACTSCAN_API_KEY}"
abstractscan_testnet = "${ABSTRACTSCAN_API_KEY}"
basescan_mainnet = "${BASESCAN_API_KEY}"
basescan_testnet = "${BASESCAN_API_KEY}"
merlinscan_mainnet = "${MERLINSCAN_API_KEY}"
merlinscan_testnet = "${MERLINSCAN_API_KEY}"
arbiscan_one = "${ARBISCAN_API_KEY}"
arbiscan_testnet = "${ARBISCAN_API_KEY}"
apescan_mainnet = "${APESCAN_API_KEY}"
apescan_testnet = "${APESCAN_API_KEY}"

[fmt]
line_length = 100
number_underscore = "thousands"
